const isoAliases = {
  ALG: 'DZA',
  ANG: 'AGO',
  ANT: 'ATG',
  BAH: 'BHS',
  BAN: 'BGD',
  BAR: 'BRB',
  BER: 'BMU',
  BHU: 'BTN',
  BOT: 'BWA',
  BRN: 'BHR',
  BRU: 'BRN',
  BUL: 'BGR',
  BUR: 'BFA',
  CAM: 'KHM',
  CAY: 'CYM',
  CGO: 'COG',
  CHA: 'TCD',
  CHI: 'CHL',
  CRC: 'CRI',
  CRO: 'HRV',
  DEN: 'DNK',
  ESA: 'SLV',
  FIJ: 'FJI',
  GAM: 'GMB',
  GBS: 'GNB',
  GEQ: 'GNQ',
  GER: 'DEU',
  GRE: 'GRC',
  GRN: 'GRD',
  GUA: 'GTM',
  GUI: 'GIN',
  HAI: 'HTI',
  HON: 'HND',
  INA: 'IDN',
  IRI: 'IRN',
  ISV: 'VIR',
  IVB: 'VGB',
  KOS: 'XKX',
  KSA: 'SAU',
  KUW: 'KWT',
  LAT: 'LVA',
  LBA: 'LBY',
  LES: 'LSO',
  LIB: 'LBN',
  MAD: 'MDG',
  MAS: 'MYS',
  MAW: 'MWI',
  MGL: 'MNG',
  MON: 'MCO',
  MRI: 'MUS',
  MTN: 'MRT',
  MYA: 'MMR',
  NCA: 'NIC',
  NED: 'NLD',
  NEP: 'NPL',
  NGR: 'NGA',
  NIG: 'NER',
  OMA: 'OMN',
  PAR: 'PRY',
  PHI: 'PHL',
  PLE: 'PSE',
  POR: 'PRT',
  PUR: 'PRI',
  RSA: 'ZAF',
  SLO: 'SVN',
  SOL: 'SLB',
  SRI: 'LKA',
  SUD: 'SDN',
  SUI: 'CHE',
  TAN: 'TZA',
  TGA: 'TON',
  TOG: 'TGO',
  TPE: 'TWN',
  UAE: 'ARE',
  URU: 'URY',
  VAN: 'VUT',
  VIE: 'VNM',
  VIN: 'VCT',
  ZAM: 'ZMB',
  ZIM: 'ZWE',
};
const normalize = (s) =>
  String(s || '')
    .normalize('NFC')
    .trim()
    .replace(/\s+/g, ' ')
    .toUpperCase();
// Codes des comités nationaux (CIO). Une liste d'engagés nationale porte le club à la place de la nation :
// un sigle de club de 3 lettres (« CEP », « SCR »…) ne doit jamais passer pour une nationalité.
const NATIONS = new Set([
  'AFG',
  'ALB',
  'ALG',
  'AND',
  'ANG',
  'ANT',
  'ARG',
  'ARM',
  'ARU',
  'ASA',
  'AUS',
  'AUT',
  'AZE',
  'BAH',
  'BAN',
  'BAR',
  'BDI',
  'BEL',
  'BEN',
  'BER',
  'BHU',
  'BIH',
  'BIZ',
  'BLR',
  'BOL',
  'BOT',
  'BRA',
  'BRN',
  'BRU',
  'BUL',
  'BUR',
  'CAF',
  'CAM',
  'CAN',
  'CAY',
  'CGO',
  'CHA',
  'CHI',
  'CHN',
  'CIV',
  'CMR',
  'COD',
  'COK',
  'COL',
  'COM',
  'CPV',
  'CRC',
  'CRO',
  'CUB',
  'CYP',
  'CZE',
  'DEN',
  'DJI',
  'DMA',
  'DOM',
  'ECU',
  'EGY',
  'ERI',
  'ESA',
  'ESP',
  'EST',
  'ETH',
  'FIJ',
  'FIN',
  'FRA',
  'FSM',
  'GAB',
  'GAM',
  'GBR',
  'GBS',
  'GEO',
  'GEQ',
  'GER',
  'GHA',
  'GRE',
  'GRN',
  'GUA',
  'GUI',
  'GUM',
  'GUY',
  'HAI',
  'HKG',
  'HON',
  'HUN',
  'INA',
  'IND',
  'IRI',
  'IRL',
  'IRQ',
  'ISL',
  'ISR',
  'ISV',
  'ITA',
  'IVB',
  'JAM',
  'JOR',
  'JPN',
  'KAZ',
  'KEN',
  'KGZ',
  'KIR',
  'KOR',
  'KOS',
  'KSA',
  'KUW',
  'LAO',
  'LAT',
  'LBA',
  'LBN',
  'LBR',
  'LCA',
  'LES',
  'LIE',
  'LTU',
  'LUX',
  'MAD',
  'MAR',
  'MAS',
  'MAW',
  'MDA',
  'MDV',
  'MEX',
  'MGL',
  'MHL',
  'MKD',
  'MLI',
  'MLT',
  'MNE',
  'MON',
  'MOZ',
  'MRI',
  'MTN',
  'MYA',
  'NAM',
  'NCA',
  'NED',
  'NEP',
  'NGR',
  'NIG',
  'NOR',
  'NRU',
  'NZL',
  'OMA',
  'PAK',
  'PAN',
  'PAR',
  'PER',
  'PHI',
  'PLE',
  'PLW',
  'PNG',
  'POL',
  'POR',
  'PRK',
  'PUR',
  'QAT',
  'ROU',
  'RSA',
  'RUS',
  'RWA',
  'SAM',
  'SEN',
  'SEY',
  'SGP',
  'SKN',
  'SLE',
  'SLO',
  'SMR',
  'SOL',
  'SOM',
  'SRB',
  'SRI',
  'SSD',
  'STP',
  'SUD',
  'SUI',
  'SUR',
  'SVK',
  'SWE',
  'SWZ',
  'SYR',
  'TAN',
  'TGA',
  'THA',
  'TJK',
  'TKM',
  'TLS',
  'TOG',
  'TPE',
  'TTO',
  'TUN',
  'TUR',
  'TUV',
  'UAE',
  'UGA',
  'UKR',
  'URU',
  'USA',
  'UZB',
  'VAN',
  'VEN',
  'VIE',
  'VIN',
  'YEM',
  'ZAM',
  'ZIM',
]);
function countryFor(roster, name) {
  const found = (Array.isArray(roster) ? roster : []).filter((r) => normalize(r.name) === normalize(name));
  if (found.length !== 1) return null;
  const code = normalize(found[0].country);
  if (!/^[A-Z]{3}$/.test(code)) return null;
  const iso = isoAliases[code] || code;
  return NATIONS.has(code) || Object.values(isoAliases).includes(code) ? iso : null;
}
function withCountries(match) {
  const { podiumRoster, ...competition } = match.competition || {};
  return {
    ...match,
    competition,
    // Code olympique, comme dans les poules (GER, SUI…), plus parlant pour les escrimeurs.
    player1Country: olympicCodeFor(podiumRoster, match.player1),
    player2Country: olympicCodeFor(podiumRoster, match.player2),
  };
}
// Code olympique (CIO) tel que publié dans la liste des engagés : FRA, GER, SUI…
function olympicCodeFor(roster, name) {
  const found = (Array.isArray(roster) ? roster : []).filter((r) => normalize(r.name) === normalize(name));
  if (found.length !== 1) return null;
  const code = normalize(found[0].country);
  return /^[A-Z]{3}$/.test(code) ? code : null;
}
// Rang d'entrée dans l'épreuve (liste des engagés FencingTimeLive), si le nom est unique.
function entryRankFor(roster, name) {
  const found = (Array.isArray(roster) ? roster : []).filter((r) => normalize(r.name) === normalize(name));
  const rank = found.length === 1 ? found[0].entryRanking : null;
  return Number.isSafeInteger(rank) && rank > 0 ? rank : null;
}
module.exports = { countryFor, olympicCodeFor, withCountries, entryRankFor };
