CREATE TABLE IF NOT EXISTS "Club" ("id" SERIAL PRIMARY KEY, "name" TEXT NOT NULL, "nameKey" TEXT NOT NULL, "description" TEXT NOT NULL DEFAULT '', "shortName" TEXT NOT NULL DEFAULT '', "city" TEXT NOT NULL DEFAULT '', "status" TEXT NOT NULL DEFAULT 'PENDING', "source" TEXT NOT NULL DEFAULT 'USER', "leagueId" INTEGER REFERENCES "League"("id") ON DELETE SET NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX IF NOT EXISTS "Club_nameKey_key" ON "Club"("nameKey");
CREATE UNIQUE INDEX IF NOT EXISTS "Club_leagueId_key" ON "Club"("leagueId");
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "clubId" INTEGER REFERENCES "Club"("id");
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "clubChoiceAt" TIMESTAMP(3);
CREATE TABLE IF NOT EXISTS "ClubResponsibility" ("id" SERIAL PRIMARY KEY, "clubId" INTEGER NOT NULL REFERENCES "Club"("id"), "userId" INTEGER NOT NULL REFERENCES "User"("id") ON DELETE CASCADE, "status" TEXT NOT NULL DEFAULT 'PENDING', "reason" TEXT NOT NULL, "reviewedBy" INTEGER, "reviewedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX IF NOT EXISTS "ClubResponsibility_clubId_userId_key" ON "ClubResponsibility"("clubId","userId");
CREATE INDEX IF NOT EXISTS "ClubResponsibility_status_idx" ON "ClubResponsibility"("status");
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('ACADEMIE ESCRIME VAUBAN LILLE','academie escrime vauban lille','LILLE VAUB','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('Antony Sport Escrime','antony sport escrime','ASE','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('BESANCON RC ESCRIME','besancon rc escrime','BESANCON RC','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('BLR92','blr92','BLR92','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('C.E. DE CHAMBERY','c e de chambery','CHAMBERY','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('C.E. DE HAGUENAU','c e de haguenau','HAGUENEAU','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('C.E. DE L''U.S. VANDOEUVRE','c e de l u s vandoeuvre','VANDOEUVRE','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('C.E. DE MEAUX','c e de meaux','MEAUX','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('C.E. DE TORCY','c e de torcy','CE Torcy','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('C.E. ROCHELAIS','c e rochelais','CE Rochelais','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('C.E. SANARYEN','c e sanaryen','CE Canarien','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('C.E. VERSAILLAIS','c e versaillais','CEV','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('CE BITERROIS','ce biterrois','CE Biterrois','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('CE DE CLERMONT','ce de clermont','CE Clermont','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('CE DE HENIN BEAUMONT','ce de henin beaumont','CE HENIN','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('CE DE MEUNG SUR LOIRE','ce de meung sur loire','CE MEUNG','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('CE DE REIMS','ce de reims','CE REIMS','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('CE DE ROUEN','ce de rouen','CE ROUEN','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('CE DE RUEIL-MALMAISON','ce de rueil malmaison','CE RUEIL','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('CE G. TAINTURIER COMPIEGNE','ce g tainturier compiegne','COMPIEGNE','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('CE RHODANIEN','ce rhodanien','RHODEZ','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('CERCLE D''ESCRIME DE SAINT LO','cercle d escrime de saint lo','SAINT LO','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('CERCLE D''ESCRIME SURESNOIS','cercle d escrime suresnois','SURESNES','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('CERCLE DES ESCRIMEURS PARISIENS','cercle des escrimeurs parisiens','CEP Paris','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('CERCLE ESCRIME FRANCO CUBAIN','cercle escrime franco cubain','CEFC','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('CS BAYEUX ESCRIME','cs bayeux escrime','BAYEUX','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('ESCRIME CLUB DE VILLEBON','escrime club de villebon','VILLEBON','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('ESCRIME CLUB LES LOGES','escrime club les loges','LES LOGES','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('ESCRIME ECULLY','escrime ecully','ECULLY','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('ESCRIME PARIS NORD','escrime paris nord','EPN','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('ESCRIME PAYS D''AIX EN PROVENCE','escrime pays d aix en provence','EPA','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('ESCRIME SUD LOIRE 45','escrime sud loire 45','LOIRE 45','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('LA RAPIERE DE GRENOBLE','la rapiere de grenoble','GRENOBLE','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('LES DUELLISTES PARIS','les duellistes paris','DUELLSITES','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('LES PIEUX','les pieux','LES PIEUX','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('LES TROIS ARMES DE SENLIS','les trois armes de senlis','3 ARMES SENLIS','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('MARSEILLE ESCRIME CLUB','marseille escrime club','MARSEILLE','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('MASQUE DE FER DE LYON','masque de fer de lyon','MDF LYON','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('MELUN VAL DE SEINE','melun val de seine','CEMVS','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('MOUSQUETAIRES D''ISSY LES MOULINEAUX','mousquetaires d issy les moulineaux','ISSY','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('NEC ESCRIME','nec escrime','NEC','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('O.G.C. NICE ESCRIME','o g c nice escrime','OGC Nice','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('OLYMPIQUE CALAS CABRIES','olympique calas cabries','OCC','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('RED STAR CLUB CHAMPIGNY','red star club champigny','CHAMPIGNY','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('SAINT PAULOISE ESCRIME CLUB','saint pauloise escrime club','SAINT PAULOISE','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('SCO ANGERS','sco angers','SCO','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('SE DU BORDEAUX EC','se du bordeaux ec','BEC','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('SGLP Escrime','sglp escrime','SGLP','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('SOCIETE D''ESCRIME DE LYON','societe d escrime de lyon','SEL','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('SPORTING CLUB UNIVERSITAIRE DE FRANCE PARIS','sporting club universitaire de france paris','SCUF','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('SQY ESCRIME CLUB','sqy escrime club','SQY','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('Stade Poitevin Escrime','stade poitevin escrime','POITIERS','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('TEAM FLEURET','team fleuret','TEAM FLEURET','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('TOULOUSE UNIVERSITE CLUB','toulouse universite club','TUC','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('Tour d''Auvergne Paris','tour d auvergne paris','TA Paris','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
INSERT INTO "Club" ("name","nameKey","shortName","status","source") VALUES ('VAL D''ORGE ESCRIME','val d orge escrime','VOE','LISTED','USER_CSV') ON CONFLICT ("nameKey") DO NOTHING;
