ALTER TABLE "ClubRegistrationRequest" ADD COLUMN IF NOT EXISTS "adminAlertStatus" TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE "ClubRegistrationRequest" ADD COLUMN IF NOT EXISTS "adminAlertAttempts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ClubRegistrationRequest" ADD COLUMN IF NOT EXISTS "adminAlertNextAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
