ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "pointsPending" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "progressionConfirmedAt" TIMESTAMP(3);
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "manualResultConfirmed" BOOLEAN NOT NULL DEFAULT false;
