ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "isLocked" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "startsAt" TIMESTAMP(3);
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "sourceUrl" TEXT;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "sourceKey" TEXT;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "sourceCheckedAt" TIMESTAMP(3);
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "round" TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS "Match_competitionId_sourceKey_key" ON "Match"("competitionId", "sourceKey");
